name:conf-demo

on:
    workflow

 env:
      a:hello
      b:how are you
      c:aws
jobs:
     greetings-job
     runs-on:ubuntu-latest

     steps: 
            name: say greetings
            run: echo " $a $b $c "
            
           
