name: context-variable

on:
  workflow_dispatch

env:
  a: google-cloud
  b: aws

jobs:
  test_context_variable:
    runs-on: ubuntu-latest

    steps:  # This line should be indented correctly (2 spaces inside the job)
      - name: "checking context variable"
        run: |
          echo "repository name : ${{ github.repository }} "
          echo "workflow name : ${{ github.workflow }} "
